project_id = "xseklnmgggguikzkmvjb"

[functions.generate-resume]
verify_jwt = false

[functions.compile-latex]
verify_jwt = false

[functions.scrape-jobs]
verify_jwt = false

[functions.fetch-job-description]
verify_jwt = false

[functions.reward-model]
verify_jwt = false
